### ISSUE TITLE
Implement `DecodedNode` and necessary methods

### ISSUE THREAD

**Issue by Kirqkas** [LimeChain/java-host#260]
Subtask of [#242](https://github.com/LimeChain/Fruzhin/issues/242)

The `DecodedNode` is a DTO in our implementation, analogous to [this struct](https://github.com/smol-dot/smoldot/blob/200214a571af30b5fa3997aea988451adc235ed0/lib/src/trie/trie_node.rs#L464) from Smoldot.

The functionality to work with it, mainly:
- [x] [`decode()`](https://github.com/smol-dot/smoldot/blob/200214a571af30b5fa3997aea988451adc235ed0/lib/src/trie/trie_node.rs#L317) to obtain it from an encoding (a `byte[]` for what we care)
    - lax priority
- [ ] [`encode()`](https://github.com/smol-dot/smoldot/blob/200214a571af30b5fa3997aea988451adc235ed0/lib/src/trie/trie_node.rs#L32) to encode it into a `byte[]`
    - 🔴 high priority
- [ ] [`calculate_merkle_value()`](https://github.com/smol-dot/smoldot/blob/200214a571af30b5fa3997aea988451adc235ed0/lib/src/trie/trie_node.rs#L176) to obtain its merkle value
    - 🔴 high priority; depends on `encode()`

is found in the `trie_node.rs` module, where the `Decoded` struct resides. We have a corresponding package to that module, where all things related to the `DecodedNode` will reside.

We need this DTO to actually calculate the merkle values of the nodes on storage initialization, like [here](https://github.com/smol-dot/smoldot/blob/200214a571af30b5fa3997aea988451adc235ed0/full-node/src/lib.rs#L935).

**Comment by David-Petrov** [comment]
`encode()` and `calculate_merkle_value()` are ready, but untested as of right now, since it's a big task without a `decode()` method, which remains to be implemented, after which we can easily construct a test suite using real encoded nodes: decode them, inspect expected properties, then encode and compare the result to the previous encoding we started with. 
Ideally, we'd want to replicate [this test](https://github.com/smol-dot/smoldot/blob/200214a571af30b5fa3997aea988451adc235ed0/lib/src/trie/trie_node.rs#L620).
