### ISSUE TITLE
Deprecate the old Trie implementation

### ISSUE THREAD

**Issue by Kirqkas** [LimeChain/java-host#270]
Think about deprecating (thus removing) the existing old Trie implementation (the Gossamer inspired one) from the `com/limechain/trie` package in favour of our new, potentially better suited and wider implementation.
I'm not currently sure whether this is feasible since I haven't investigated the use case for loading the runtime, but it'll most probably not be a problem. :)

**Comment by David-Petrov** [comment]
Turns out both implementation are kind of built for the reverse purposes:
- the old `Trie` is built by given encoded proof and provides the ability to query the built trie storage for a known key (for its corresponding value); i.e. `proof encoding -> storage`;
- the new `TrieStructure` is easily built from existing (known) storage (i.e. KVPs) and is rather able to provide (with some additional work) proofs; i.e. `storage -> proof encoding`.

We're leaving them both coexisting for now.
